package org.SkyCraftTeam.SkyCraft.Utils;

import org.SkyCraftTeam.SkyCraft.Main;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.ShapedRecipe;

public class CraftHandler {
	
	public CraftHandler(Main main) {
		ItemStack lp = main.getIItems().getLockpick();
		ItemStack ol1 = main.getIItems().getLock("order", "novice");
		ItemStack ol2 = main.getIItems().getLock("order", "adept");
		ItemStack ol3 = main.getIItems().getLock("order", "master");
		ItemStack ol4 = main.getIItems().getLock("order", "expert");
		ItemStack ml1 = main.getIItems().getLock("maze", "novice");
		ItemStack ml2 = main.getIItems().getLock("maze", "adept");
		ItemStack ml3 = main.getIItems().getLock("maze", "master");
		ItemStack ml4 = main.getIItems().getLock("maze", "expert");
		ItemStack pl1 = main.getIItems().getLock("push", "novice");
		ItemStack pl2 = main.getIItems().getLock("push", "adept");
		ItemStack pl3 = main.getIItems().getLock("push", "master");
		ItemStack pl4 = main.getIItems().getLock("push", "expert");
		ShapedRecipe lpr = new ShapedRecipe(new NamespacedKey(main, "lpr"), lp);
		ShapedRecipe ol1r = new ShapedRecipe(new NamespacedKey(main, "ol1r"), ol1);
		ShapedRecipe ol2r = new ShapedRecipe(new NamespacedKey(main, "ol2r"), ol2);
		ShapedRecipe ol3r = new ShapedRecipe(new NamespacedKey(main, "ol3r"), ol3);
		ShapedRecipe ol4r = new ShapedRecipe(new NamespacedKey(main, "ol4r"), ol4);
		ShapedRecipe ml1r = new ShapedRecipe(new NamespacedKey(main, "ml1r"), ml1);
		ShapedRecipe ml2r = new ShapedRecipe(new NamespacedKey(main, "ml2r"), ml2);
		ShapedRecipe ml3r = new ShapedRecipe(new NamespacedKey(main, "ml3r"), ml3);
		ShapedRecipe ml4r = new ShapedRecipe(new NamespacedKey(main, "ml4r"), ml4);
		ShapedRecipe pl1r = new ShapedRecipe(new NamespacedKey(main, "pl1r"), pl1);
		ShapedRecipe pl2r = new ShapedRecipe(new NamespacedKey(main, "pl2r"), pl2);
		ShapedRecipe pl3r = new ShapedRecipe(new NamespacedKey(main, "pl3r"), pl3);
		ShapedRecipe pl4r = new ShapedRecipe(new NamespacedKey(main, "pl4r"), pl4);
		lpr.shape("   ", "  *", " % ");
		lpr.setIngredient('*', Material.IRON_NUGGET);
		lpr.setIngredient('%', Material.IRON_INGOT);
		ol1r.shape(" * ", "*$*", "%%%");
		ol1r.setIngredient('*', Material.IRON_NUGGET);
		ol1r.setIngredient('%', Material.IRON_INGOT);
		ol1r.setIngredient('$', Material.REDSTONE);
		ol2r.shape(" * ", "*$*", "%%%");
		ol2r.setIngredient('*', Material.IRON_NUGGET);
		ol2r.setIngredient('%', Material.IRON_INGOT);
		ol2r.setIngredient('$', Material.GOLD_INGOT);
		ol3r.shape(" * ", "*$*", "%%%");
		ol3r.setIngredient('*', Material.IRON_NUGGET);
		ol3r.setIngredient('%', Material.IRON_INGOT);
		ol3r.setIngredient('$', Material.DIAMOND);
		ol4r.shape(" * ", "*$*", "%%%");
		ol4r.setIngredient('*', Material.IRON_NUGGET);
		ol4r.setIngredient('%', Material.IRON_INGOT);
		ol4r.setIngredient('$', Material.EMERALD);
		ml1r.shape(" * ", "%$%", "%%%");
		ml1r.setIngredient('*', Material.IRON_NUGGET);
		ml1r.setIngredient('%', Material.IRON_INGOT);
		ml1r.setIngredient('$', Material.REDSTONE);
		ml2r.shape(" * ", "%$%", "%%%");
		ml2r.setIngredient('*', Material.IRON_NUGGET);
		ml2r.setIngredient('%', Material.IRON_INGOT);
		ml2r.setIngredient('$', Material.GOLD_INGOT);
		ml3r.shape(" * ", "%$%", "%%%");
		ml3r.setIngredient('*', Material.IRON_NUGGET);
		ml3r.setIngredient('%', Material.IRON_INGOT);
		ml3r.setIngredient('$', Material.DIAMOND);
		ml4r.shape(" * ", "%$%", "%%%");
		ml4r.setIngredient('*', Material.IRON_NUGGET);
		ml4r.setIngredient('%', Material.IRON_INGOT);
		ml4r.setIngredient('$', Material.EMERALD);
		pl1r.shape(" % ", "*$*", "%%%");
		pl1r.setIngredient('*', Material.IRON_NUGGET);
		pl1r.setIngredient('%', Material.IRON_INGOT);
		pl1r.setIngredient('$', Material.REDSTONE);
		pl2r.shape(" % ", "*$*", "%%%");
		pl2r.setIngredient('*', Material.IRON_NUGGET);
		pl2r.setIngredient('%', Material.IRON_INGOT);
		pl2r.setIngredient('$', Material.GOLD_INGOT);
		pl3r.shape(" % ", "*$*", "%%%");
		pl3r.setIngredient('*', Material.IRON_NUGGET);
		pl3r.setIngredient('%', Material.IRON_INGOT);
		pl3r.setIngredient('$', Material.DIAMOND);
		pl4r.shape(" % ", "*$*", "%%%");
		pl4r.setIngredient('*', Material.IRON_NUGGET);
		pl4r.setIngredient('%', Material.IRON_INGOT);
		pl4r.setIngredient('$', Material.EMERALD);
		main.getServer().addRecipe(lpr);
		main.getServer().addRecipe(ol1r);
		main.getServer().addRecipe(ol2r);
		main.getServer().addRecipe(ol3r);
		main.getServer().addRecipe(ol4r);
		main.getServer().addRecipe(ml1r);
		main.getServer().addRecipe(ml2r);
		main.getServer().addRecipe(ml3r);
		main.getServer().addRecipe(ml4r);
		main.getServer().addRecipe(pl1r);
		main.getServer().addRecipe(pl2r);
		main.getServer().addRecipe(pl3r);
		main.getServer().addRecipe(pl4r);
	}

}
