resourcepack:
  enabled: false
  lockpick-material: 'STICK'
  order-lock-material: 'MUSIC_DISC_STAL'
  push-lock-material: 'MUSIC_DISC_STAL'
  maze-lock-material: 'MUSIC_DISC_STAL'
  lockpick-modeldata: 1
  order-lock-modeldata: 1
  push-lock-modeldata: 2
  maze-lock-modeldata: 3
lockpick-name: '&aLockpick'
order-lock-name: '&aLock: &eorder'
push-lock-name: '&aLock: &epush'
maze-lock-name: '&aLock: &emaze'
down-arrow-name: ''
right-arrow-name: ''
inventory-name: '&dCringe'
locklevel-name: '&eLock level: &d%level%'
craft-locks: true
  